package titlemanager.panel;

import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import titlemanager.util.Login;

/**
 * Class LoginPanel menampilkan panel untuk login.
 *
 * @author Fure
 */
public class LoginPanel extends javax.swing.JPanel {
    private JScrollPane contentScrollPane;

    /**
    * Creates new form LoginPanel
    * @param contentScrollPane JScrollPane untuk menampilkan panel ini
    */
    public LoginPanel(JScrollPane contentScrollPane) {
        this.contentScrollPane = contentScrollPane;
        initComponents();
    }

    /**
     * Creates new form LoginPanel
     */
    public LoginPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        userTextField = new javax.swing.JTextField();
        PasswordField = new javax.swing.JPasswordField();
        loginButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/titlemanager/icon/icons8_user_16px.png"))); // NOI18N
        jLabel1.setLabelFor(userTextField);
        jLabel1.setText("Username");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/titlemanager/icon/icons8_password_16px.png"))); // NOI18N
        jLabel2.setLabelFor(PasswordField);
        jLabel2.setText("Password");

        userTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userTextFieldActionPerformed(evt);
            }
        });

        PasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordFieldActionPerformed(evt);
            }
        });

        loginButton.setText("Login");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });

        jLabel3.setText("Sign Up");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(loginButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(userTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(82, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {PasswordField, userTextField});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(89, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(loginButton))
                .addGap(83, 83, 83))
        );
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Method untuk melakukan login
     * @param evt
     */
    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        String username = userTextField.getText();
        String password = new String(PasswordField.getPassword());

        // Cek apakah username dan password kosong
        if (username.isEmpty() || password.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Fields tidak boleh kosong", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // Cek apakah username dan password sama dengan yang ada di database, jika sama maka login berhasil
        if (Login.getInstance().isLogin(username, password)) {
            contentScrollPane.setViewportView(new SearchPanel(contentScrollPane));
        } else {
            JOptionPane.showMessageDialog(this, "Username atau Password salah", "Gagal", JOptionPane.ERROR_MESSAGE);

            // Kosongkan field username dan password
            userTextField.setText("");
            PasswordField.setText("");

            // Focus ke username field
            userTextField.requestFocus();
        }
    }//GEN-LAST:event_loginButtonActionPerformed

    /**
     * Method untuk menuju halaman sign up
     * @param evt
     */
    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // Menuju halaman sign up
        contentScrollPane.setViewportView(new SignUpPanel(contentScrollPane));
    }//GEN-LAST:event_jLabel3MouseClicked

    /**
     * Method untuk memindahkan focus ke field password
     * @param evt
     */
    private void userTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userTextFieldActionPerformed
        // Ketika enter di tekan, maka pindah ke field password
        PasswordField.requestFocus();
    }//GEN-LAST:event_userTextFieldActionPerformed

    /**
     * Method untuk menekan login button ketika tombol enter di tekan.
     * @param evt
     */
    private void PasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordFieldActionPerformed
        // Ketika enter di tekan, maka klik tombol login
        loginButton.doClick();
    }//GEN-LAST:event_PasswordFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton loginButton;
    private javax.swing.JTextField userTextField;
    // End of variables declaration//GEN-END:variables
}
