package titlemanager.panel;

import titlemanager.model.UserProfiles;
import titlemanager.model.Project;
import titlemanager.model.Item;
import titlemanager.model.Account;
import titlemanager.util.Database;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import java.awt.Color;

/**
 * Class SearchPanel menampilkan panel untuk mencari judul project yang telah 
 * ada di database sebelum menginputkan judul project baru.
 *
 * @author Fure
 */
public class SearchPanel extends javax.swing.JPanel {
    private ArrayList<Item> itemList = new ArrayList<Item>(); // list item yang akan ditampilkan di list
    private JScrollPane     contentScrollPane;

    /**
     * Creates new form SearchPanel
     * @param contentScrollPane JScrollPane untuk menampilkan panel ini
     */
    public SearchPanel(JScrollPane contentScrollPane) {
        this.contentScrollPane = contentScrollPane;
        initComponents();
        loadListData();
        loginAsLabel();
    }

    /**
     * Creates new form SearchPanel
     */
    public SearchPanel() {
        initComponents();
        loadListData();
        loginAsLabel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        projectDialog = new javax.swing.JDialog();
        namaLabel = new javax.swing.JLabel();
        nimLabel = new javax.swing.JLabel();
        nomorLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        judulLabel = new javax.swing.JLabel();
        abstrakLabel = new javax.swing.JLabel();
        judulTextField = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        abstrakTextArea = new javax.swing.JTextArea();
        namaTextField = new javax.swing.JTextField();
        nimTextField = new javax.swing.JTextField();
        nomorTextField = new javax.swing.JTextField();
        emailTextField = new javax.swing.JTextField();
        updateButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        idTextField = new javax.swing.JTextField();
        searchTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList = new javax.swing.JList<>();
        userLabel = new javax.swing.JLabel();
        insertButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        logoutLabel = new javax.swing.JLabel();

        namaLabel.setText("Nama");

        nimLabel.setText("NIM");

        nomorLabel.setText("Telp");

        emailLabel.setText("Email");

        judulLabel.setText("Judul");

        abstrakLabel.setText("Abstrak");

        abstrakTextArea.setColumns(20);
        abstrakTextArea.setRows(5);
        jScrollPane2.setViewportView(abstrakTextArea);

        nimTextField.setEditable(false);

        updateButton.setText("Update");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        deleteButton.setText("Delete");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        idTextField.setEditable(false);

        javax.swing.GroupLayout projectDialogLayout = new javax.swing.GroupLayout(projectDialog.getContentPane());
        projectDialog.getContentPane().setLayout(projectDialogLayout);
        projectDialogLayout.setHorizontalGroup(
            projectDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(projectDialogLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(projectDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(abstrakLabel)
                    .addComponent(judulLabel)
                    .addComponent(namaLabel)
                    .addComponent(nomorLabel)
                    .addComponent(emailLabel)
                    .addComponent(nimLabel))
                .addGap(18, 18, 18)
                .addGroup(projectDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, projectDialogLayout.createSequentialGroup()
                        .addGroup(projectDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(namaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nomorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nimTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                        .addGroup(projectDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(updateButton, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(deleteButton, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(idTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane2)
                    .addComponent(judulTextField))
                .addGap(36, 36, 36))
        );

        projectDialogLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {emailTextField, namaTextField, nimTextField, nomorTextField});

        projectDialogLayout.setVerticalGroup(
            projectDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(projectDialogLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(projectDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(judulLabel)
                    .addComponent(judulTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(projectDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(abstrakLabel)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(projectDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(namaLabel)
                    .addComponent(namaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(projectDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nimLabel)
                    .addComponent(nimTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(projectDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailLabel)
                    .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(projectDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomorLabel)
                    .addComponent(nomorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteButton))
                .addGap(31, 31, 31))
        );

        searchTextField.setForeground(new java.awt.Color(102, 102, 102));
        searchTextField.setText("Masukkan Judul Project...");
        searchTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                searchTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                searchTextFieldFocusLost(evt);
            }
        });
        searchTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchTextFieldKeyReleased(evt);
            }
        });

        jScrollPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jList);

        userLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        userLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        insertButton.setText("Insert");
        insertButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertButtonActionPerformed(evt);
            }
        });

        jLabel2.setText("Judul dalam database :");

        logoutLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/titlemanager/icon/icons8_Logout_16px_2.png"))); // NOI18N
        logoutLabel.setText("Logout");
        logoutLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(logoutLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(userLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(insertButton))
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(searchTextField))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(insertButton)
                    .addComponent(userLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logoutLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addComponent(searchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {logoutLabel, userLabel});

    }// </editor-fold>//GEN-END:initComponents

    /**
     * Method untuk mengambil data dari database dan menampilkannya
     * setiap kali user mengetikkan kata.
     * @param evt
     */
    private void searchTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchTextFieldKeyReleased
        loadListData();
    }//GEN-LAST:event_searchTextFieldKeyReleased

    /**
     * Method untuk mengambil data dari database dan menampilkannya
     * ketika list di klik.
     * @param evt
     */
    private void jListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListMouseClicked
        int index = jList.getSelectedIndex();
        
        // jika list kosong maka tidak ada yang di klik / return
        if (index == -1) {
            return;
        }

        // jika list tidak kosong maka ambil data dari list item
        Item item = itemList.get(index);

        try {
            Project project = Database.getInstance().getProject(item.getValue());
            UserProfiles user = Database.getInstance().getUserProfiles(project.getNim());

            judulTextField.setText(project.getJudul());
            abstrakTextArea.setText(project.getAbstrak());
            namaTextField.setText(user.getNama());
            nimTextField.setText(user.getNim());
            emailTextField.setText(user.getEmail());
            nomorTextField.setText(user.getNomor());

            idTextField.setText(String.valueOf(project.getId()));
            idTextField.setVisible(false);  // set id invisible


            // dialog size
            projectDialog.setSize(400, 400);

            // show dialog
            projectDialog.setVisible(true);

            // show dialog di tengah layar
            projectDialog.setLocationRelativeTo(null);

            // Jika user bukan pemilik project maka tidak bisa edit
            if (!user.getNim().equals(Account.getInstance().getUsername()) 
                    && !Account.getInstance().getRole().equals("admin")) {
                // disable edit all text field
                judulTextField.setEditable(false);
                abstrakTextArea.setEditable(false);
                namaTextField.setEditable(false);
                nimTextField.setEditable(false);
                emailTextField.setEditable(false);
                nomorTextField.setEditable(false);
                updateButton.setVisible(false);
                deleteButton.setVisible(false);
            } else {
                // enable edit all text field
                judulTextField.setEditable(true);
                abstrakTextArea.setEditable(true);
                namaTextField.setEditable(true);
                emailTextField.setEditable(true);
                nomorTextField.setEditable(true);
                updateButton.setVisible(true);
                deleteButton.setVisible(true);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jListMouseClicked

    /**
     * Method untuk menuju halaman insert project.
     * @param evt
     */
    private void insertButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertButtonActionPerformed
        // cek apakah placeholder text masih ada
        if (searchTextField.getText().equals("Masukkan Judul Project...")) {
            searchTextField.setText("");
        }

        // Menuju halaman insert project
        contentScrollPane.setViewportView(new InsertPanel(contentScrollPane, searchTextField.getText()));
    }//GEN-LAST:event_insertButtonActionPerformed

    /**
     * Method untuk mengupdate data project.
     * @param evt
     */
    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        // Konfirm update dialog
        int confirm = JOptionPane.showConfirmDialog(this, "Apakah anda yakin ingin mengubah data ini?", "Konfirmasi", JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            Project project = new Project();
            project.setJudul(judulTextField.getText());
            project.setAbstrak(abstrakTextArea.getText());
            project.setNim(nimTextField.getText());
            project.setId(Integer.parseInt(idTextField.getText()));

            UserProfiles user = new UserProfiles();
            user.setNama(namaTextField.getText());
            user.setNim(nimTextField.getText());
            user.setEmail(emailTextField.getText());
            user.setNomor(nomorTextField.getText());

            try {
                Database.getInstance().updateProject(project);
                Database.getInstance().updateUserProfile(user);
                JOptionPane.showMessageDialog(this, "Berhasil mengubah data", "Berhasil",
                        JOptionPane.INFORMATION_MESSAGE);
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            // Jika batal maka muncukan dialog
            JOptionPane.showMessageDialog(this, "Batal mengubah data", "Batal", JOptionPane.INFORMATION_MESSAGE);
        }

        // load list
        loadListData();

        // close dialog
        projectDialog.dispose();
        
    }//GEN-LAST:event_updateButtonActionPerformed

    /**
     * Method untuk menghapus data project.
     * @param evt
     */
    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // Konfirm delete dialog
        int confirm = JOptionPane.showConfirmDialog(this, "Apakah anda yakin ingin menghapus data ini?", "Konfirmasi", JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            // delete data berdasarkan id
            int id = Integer.parseInt(idTextField.getText());

            try {
                Database.getInstance().deleteProject(id);
                JOptionPane.showMessageDialog(this, "Berhasil menghapus data", "Berhasil",
                        JOptionPane.INFORMATION_MESSAGE);
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            // jika batal maka munculkan dialog
            JOptionPane.showMessageDialog(this, "Batal menghapus data", "Batal", JOptionPane.INFORMATION_MESSAGE);
        }

        // load list
        loadListData();

        // close dialog
        projectDialog.dispose();

    }//GEN-LAST:event_deleteButtonActionPerformed

    /**
     * Method untuk menghilangkan placeholder text.
     * @param evt
     */
    private void searchTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchTextFieldFocusGained
        // Kosongkan placeholder text
        if (searchTextField.getText().equals("Masukkan Judul Project...")) {
            searchTextField.setText("");
            searchTextField.setForeground(new Color(187,187,187));
        }
    }//GEN-LAST:event_searchTextFieldFocusGained

    /**
     * Method untuk menampilkan placeholder text.
     * @param evt
     */
    private void searchTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchTextFieldFocusLost
        // Munculkan placeholder text ketika kosong
        if (searchTextField.getText().equals("")) {
            searchTextField.setText("Masukkan Judul Project...");
            searchTextField.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_searchTextFieldFocusLost

    /**
     * Method untuk kembali ke login (Log out).
     * @param evt
     */
    private void logoutLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutLabelMouseClicked
        // Logout menuju ke login panel dan menghapus data pada Objek Account
        contentScrollPane.setViewportView(new LoginPanel(contentScrollPane));
        
        // mengosongkan class Account
        Account.getInstance().clear();
        
        // close dialog jika ada yang terbuka
        projectDialog.dispose();
    }//GEN-LAST:event_logoutLabelMouseClicked
    

    /**
     * Method untuk menampilkan data pada list.
     */
    private void loadListData() {
        DefaultListModel<String> model = new DefaultListModel<>();
        String search = searchTextField.getText();

        // get data dari database
        try {
            itemList = Database.getInstance().getJudulByKeyword(search);

            for (Item item : itemList) {
                model.addElement(item.getDescription());
            }
        } catch (SQLException ex) {
            System.err.println(ex);
            JOptionPane.showMessageDialog(this, "Gagal mengambil data", "Gagal", JOptionPane.ERROR_MESSAGE);
        }
        
        jList.setModel(model);
    }

    /**
     * Method untuk menampilkan nama user.
     */
    private void loginAsLabel() {
        // jika user login sebagai admin maka label login sebagai admin akan muncul
        if (Account.getInstance().getRole().equals("admin")) {
            userLabel.setText("Admin");
            return;
        }

        // Menampilkan nama user
        try {
            userLabel.setText("Login as: "
                    + Database.getInstance().getUserProfiles(Account.getInstance().getUsername()).getNama());
        } catch (SQLException ex) {
            System.err.println(ex);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel abstrakLabel;
    private javax.swing.JTextArea abstrakTextArea;
    private javax.swing.JButton deleteButton;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JTextField idTextField;
    private javax.swing.JButton insertButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList<String> jList;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel judulLabel;
    private javax.swing.JTextField judulTextField;
    private javax.swing.JLabel logoutLabel;
    private javax.swing.JLabel namaLabel;
    private javax.swing.JTextField namaTextField;
    private javax.swing.JLabel nimLabel;
    private javax.swing.JTextField nimTextField;
    private javax.swing.JLabel nomorLabel;
    private javax.swing.JTextField nomorTextField;
    private javax.swing.JDialog projectDialog;
    private javax.swing.JTextField searchTextField;
    private javax.swing.JButton updateButton;
    private javax.swing.JLabel userLabel;
    // End of variables declaration//GEN-END:variables
}
