package titlemanager.panel;

import java.sql.SQLException;

import javax.swing.JOptionPane;
import javax.swing.JScrollPane;

import titlemanager.util.Database;
import titlemanager.util.Utils;

/**
 * Class SignUpPassPanel menampilkan panel untuk sign up,
 * untuk mengisi password.
 * 
 * @author Fure
 */
public class SignUpPassPanel extends javax.swing.JPanel {
    private JScrollPane contentScrollPane;
    private String username;
    /**
     * Creates new form SignUpPass
     * @param contentScrollPane JScrollPane untuk menampilkan panel ini
     * @param username username untuk index database
     */
    public SignUpPassPanel(JScrollPane contentScrollPane, String username) {
        this.contentScrollPane = contentScrollPane;
        this.username = username;
        initComponents();
        usernameTextField.setText(username);
        passwordField.requestFocus();
    }

    /**
     * Creates new form SignUpPass
     */
    public SignUpPassPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        usernameTextField = new javax.swing.JTextField();
        passwordField = new javax.swing.JPasswordField();
        confirmPasswordField = new javax.swing.JPasswordField();
        saveButton = new javax.swing.JButton();
        passwordLabel = new javax.swing.JLabel();
        pasword2Label = new javax.swing.JLabel();
        usernameLabel = new javax.swing.JLabel();
        backLabel = new javax.swing.JLabel();

        usernameTextField.setEditable(false);

        passwordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordFieldActionPerformed(evt);
            }
        });

        confirmPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmPasswordFieldActionPerformed(evt);
            }
        });

        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        passwordLabel.setText("Password");

        pasword2Label.setText("Konfirmasi Password");

        usernameLabel.setText("Username / NIM");

        backLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/titlemanager/icon/icons8_return_32px_1.png"))); // NOI18N
        backLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(passwordLabel)
                        .addGap(92, 92, 92)
                        .addComponent(passwordField, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(usernameLabel)
                        .addGap(55, 55, 55)
                        .addComponent(usernameTextField))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pasword2Label)
                            .addComponent(backLabel))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(confirmPasswordField))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(saveButton)))))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usernameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pasword2Label))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(saveButton)
                    .addComponent(backLabel))
                .addGap(72, 72, 72))
        );
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Method untuk menyimpan data form ke database
     * @param evt
     */
    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        String password = new String(passwordField.getPassword());
        String confirmPassword = new String(confirmPasswordField.getPassword());
        // Field validation
        if (password.equals("") || confirmPassword.equals("")) {
            JOptionPane.showMessageDialog(this, "Password tidak boleh kosong", "Error", JOptionPane.ERROR_MESSAGE);
            clearForm();
            return;
        }
        // yes or no dialog
        int reply = JOptionPane.showConfirmDialog(null, "Apakah anda yakin ingin menyimpan password?", "Konfirmasi",
                JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION) {

            if (password.equals(confirmPassword)) {
                try {
                    Database.getInstance().setUser(username, Utils.encryptPassword(password));
                    JOptionPane.showMessageDialog(this, "Sign Up Success");
                    contentScrollPane.setViewportView(new LoginPanel(contentScrollPane));
                } catch (Exception e) {
                    System.out.println(e.getMessage());
                    JOptionPane.showMessageDialog(this, "Sign Up Failed", "Error", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Password tidak sama");
            }
        }
        clearForm();
    }//GEN-LAST:event_saveButtonActionPerformed

    /**
     * Method untuk mengubah fokus ke field berikutnya
     * @param evt
     */
    private void passwordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordFieldActionPerformed
        confirmPasswordField.requestFocus();
    }//GEN-LAST:event_passwordFieldActionPerformed

    /**
     * Method untuk mengubah fokus ke field berikutnya
     * @param evt
     */
    private void confirmPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmPasswordFieldActionPerformed
        saveButton.doClick();
    }//GEN-LAST:event_confirmPasswordFieldActionPerformed

    /**
     * Method untuk kembali ke panel login dan menghapus data user yang sudah
     * dimasukkan sebelumnya
     * @param evt
     */
    private void backLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backLabelMouseClicked
        // hapus data user profile 
        try {
            Database.getInstance().deleteUserProfile(username);
        } catch (SQLException e) {
            e.printStackTrace();
        }

        // kembali ke login panel
        contentScrollPane.setViewportView(new LoginPanel(contentScrollPane));
    }//GEN-LAST:event_backLabelMouseClicked

    /**
     * Method untuk membersihkan field
     */
    private void clearForm() {
        passwordField.setText("");
        confirmPasswordField.setText("");
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backLabel;
    private javax.swing.JPasswordField confirmPasswordField;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JLabel pasword2Label;
    private javax.swing.JButton saveButton;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JTextField usernameTextField;
    // End of variables declaration//GEN-END:variables
}
