package titlemanager.panel;

import titlemanager.model.UserProfiles;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import titlemanager.util.Database;

/**
 * Class SignUpPanel untuk menampilkan panel sign up
 * 
 * @author Fure
 */
public class SignUpPanel extends javax.swing.JPanel {
    private JScrollPane contentScrollPane;

    /**
     * Creates new form SIgnUpPanel
     * @param contentScrollPane scroll pane yang akan diisi dengan panel ini
     */
    public SignUpPanel(JScrollPane contentScrollPane) {
        this.contentScrollPane = contentScrollPane;
        initComponents();
    }

    public SignUpPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nimTextField = new javax.swing.JTextField();
        namaTextField = new javax.swing.JTextField();
        emailTextField = new javax.swing.JTextField();
        nomorTextField = new javax.swing.JTextField();
        nimLabel = new javax.swing.JLabel();
        namaLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        nomorLabel = new javax.swing.JLabel();
        backLabel = new javax.swing.JLabel();
        nextButton = new javax.swing.JButton();

        nimTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nimTextFieldActionPerformed(evt);
            }
        });

        namaTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaTextFieldActionPerformed(evt);
            }
        });

        emailTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTextFieldActionPerformed(evt);
            }
        });

        nomorTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomorTextFieldActionPerformed(evt);
            }
        });

        nimLabel.setText("NIM");

        namaLabel.setText("Nama");

        emailLabel.setText("Email");

        nomorLabel.setText("Nomor");

        backLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/titlemanager/icon/icons8_return_32px_1.png"))); // NOI18N
        backLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backLabelMouseClicked(evt);
            }
        });

        nextButton.setText("next");
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nimLabel)
                    .addComponent(namaLabel)
                    .addComponent(emailLabel)
                    .addComponent(nomorLabel)
                    .addComponent(backLabel))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(nimTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(namaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(nextButton)
                        .addGap(2, 2, 2)))
                .addContainerGap(85, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {emailTextField, namaTextField, nimTextField, nomorTextField});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nimLabel)
                    .addComponent(nimTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namaLabel)
                    .addComponent(namaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailLabel)
                    .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomorLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nextButton)
                    .addComponent(backLabel))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {emailTextField, namaTextField, nextButton, nimTextField, nomorTextField});

    }// </editor-fold>//GEN-END:initComponents

    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
        UserProfiles user = new UserProfiles();
        user.setNim(nimTextField.getText());
        user.setNama(namaTextField.getText());
        user.setEmail(emailTextField.getText());
        user.setNomor(nomorTextField.getText());
        
        // check if textField is already filled
        if (nimTextField.getText().isEmpty() || namaTextField.getText().isEmpty() || emailTextField.getText().isEmpty()
                || nomorTextField.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please fill all the textFields");
        } else {

            // konfirimasi
            int result = JOptionPane.showConfirmDialog(this, "Apakah anda yakin ingin menyimpan data ini?",
                    "Konfirmasi", JOptionPane.YES_NO_OPTION);
            if (result == JOptionPane.YES_OPTION) {
                // simpan data
                try {
                    Database.getInstance().insertProfile(user);
                    contentScrollPane.setViewportView(new SignUpPassPanel(contentScrollPane, user.getNim()));
                } catch (SQLException ex) {
                    System.err.println(ex);
                    JOptionPane.showMessageDialog(this, "Gagal menyimpan data", "Gagal", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
        clearForm();
        nimTextField.requestFocus();
    }//GEN-LAST:event_nextButtonActionPerformed

    /**
     * Mengubah fokus ke field berikutnya
     * @param evt
     */
    private void nimTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nimTextFieldActionPerformed
        // jika enter ditekan, menuju ke field berikutnya
        namaTextField.requestFocus();
    }//GEN-LAST:event_nimTextFieldActionPerformed

    /**
     * Mengubah fokus ke field berikutnya
     * @param evt
     */
    private void namaTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaTextFieldActionPerformed
        // jika enter ditekan, menuju ke field berikutnya
        emailTextField.requestFocus();
    }//GEN-LAST:event_namaTextFieldActionPerformed

    /**
     * Mengubah fokus ke field berikutnya
     * @param evt
     */
    private void emailTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTextFieldActionPerformed
        // jika enter ditekan, menuju ke field berikutnya
        nomorTextField.requestFocus();
    }//GEN-LAST:event_emailTextFieldActionPerformed

    /**
     * Mengubah fokus ke field berikutnya
     * @param evt
     */
    private void nomorTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomorTextFieldActionPerformed
        // jika enter ditekan, menuju ke field berikutnya
        nextButton.doClick();
    }//GEN-LAST:event_nomorTextFieldActionPerformed

    /**
     * Mengubah fokus ke field berikutnya
     * @param evt
     */
    private void backLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backLabelMouseClicked
        // kembali ke login panel
        contentScrollPane.setViewportView(new LoginPanel(contentScrollPane));
    }//GEN-LAST:event_backLabelMouseClicked

    /**
     * Mengosongkan fields
     */
    private void clearForm() {
        nimTextField.setText("");
        namaTextField.setText("");
        emailTextField.setText("");
        nomorTextField.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backLabel;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JLabel namaLabel;
    private javax.swing.JTextField namaTextField;
    private javax.swing.JButton nextButton;
    private javax.swing.JLabel nimLabel;
    private javax.swing.JTextField nimTextField;
    private javax.swing.JLabel nomorLabel;
    private javax.swing.JTextField nomorTextField;
    // End of variables declaration//GEN-END:variables
}
